routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\TariffController;
use App\Http\Controllers\Admin\TariffDetailsController;
use App\Http\Controllers\Admin\InterestController;
use App\Http\Controllers\Admin\GenersController;
use App\Http\Controllers\Admin\CountryController;
use App\Http\Controllers\Admin\Analytics\UsersController as AnalyticsUsersController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[LoginController::class,'index'])->name('login');
Route::get('/login',[LoginController::class,'login']);
Route::post('/login',[LoginController::class,'auth'])->name('auth');

Route::group(['prefix' => 'admin', 'middleware'=> ['roles:admin'],'as' => 'admin.'], function () {
    Route::get('/',[AnalyticsUsersController::class, 'mainPage'])->name('list');
    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/',[UsersController::class, 'index'])->name('list');
        Route::get('show/{user}',[UsersController::class, 'show'])->name('show');
        Route::get('/destroy/{user}',[UsersController::class, 'destroy'])->name('destroy');
    });

    Route::resource('tariffs',TariffController::class);
    Route::resource('tariff_details', TariffDetailsController::class);
    Route::resource('interests',  InterestController::class);
    Route::get('interests/destroy/{id}', [InterestController::class,'destroy'])->name('interests.destroy');
    Route::resource('geners', GenersController::class);
    Route::get('geners/list/{zhuz}', [GenersController::class, 'listByZhuz'])->name('geners.list');
    Route::get('delete/{id}', [GenersController::class, 'destroy'])->name('geners.delete');
    Route::group(['prefix' => 'countries', 'as' => 'countries.'], function () {
        Route::get('/',[CountryController::class, 'listOfCountries'])->name('list_of_countries');
        Route::get('create',[CountryController::class, 'createCountry'])->name('create-country');
        Route::post('store-countries', [CountryController::class, 'postCountry'])->name('store-countries');
        Route::any('update-country/{country}', [CountryController::class, 'editCountry'])->name('update-country');

        Route::get('list-cities/{region}',[CountryController::class, 'listOfCities'])->name('list_of_cities');
        Route::get('list-region/{country}',[CountryController::class, 'listOfRegion'])->name('list_of_region');
        Route::get('remove',[CountryController::class, 'remove'])->name('remove');

        Route::get('create-city',[CountryController::class, 'createCity'])->name('create-city');
        Route::get('create-region',[CountryController::class, 'createRegion'])->name('create-region');

        Route::post('store-cities', [CountryController::class, 'postCity'])->name('store-cities');
        Route::any('update-city/{city}', [CountryController::class, 'editCity'])->name('update-city');
        Route::any('update-region/{region}', [CountryController::class, 'editRegion'])->name('update-region');

        Route::post('store-region', [CountryController::class, 'postRegion'])->name('store-region');

    });
});

Route::get('terms', function () {
    echo 'terms';
});

Route::get('privacy', function () {
    echo 'privacy';
});

app/Models/Tariff.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\DB;

class Tariff extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'price','description'
    ];

    /**
     * @return HasMany
     */
    public function details(): HasMany
    {
        return $this->hasMany(TariffDetail::class);
    }

    public function profit()
    {
        return Tariff::where('created_at')
               ->join('user_tariffs', 'tariffs.id','=', 'user_tariffs.tariff_id')
               ->select('tariffs.name','SUM(tariffs.price)',DB::raw('count(user_tariffs.user_id) as users_count'))
               ->groupBy('tariffs.name');
    }

    /**
     * @return BelongsTo
     */
    public function userTariff(): BelongsTo
    {
        return $this->belongsTo(UserTariff::class);
    }

    /**
     * @return HasMany
     */
    public function prices(): HasMany
    {
        return $this->hasMany(TariffPrice::class);
    }

    /**
     * @return HasMany
     */
    public function images(): HasMany
    {
        return $this->hasMany(ImageTariff::class);
    }
}

app/Http/Controllers/Admin/Analytics/TariffController.php
<?php

namespace App\Http\Controllers\Admin\Analytics;

use App\Http\Controllers\Controller;
use App\Models\UserTariff;
use Illuminate\Http\Request;
use Illuminate\View\View;

class TariffController extends Controller
{


    /**
     * @return View
     */
    public function popularTariff(): View
    {
        $tariff = UserTariff::selectRaw("tariff_id, count(id) as populars")
            ->groupBy('tariff_id')
            ->orderBy('populars','DESC')
            ->get();

        return view('admin.analytics.popular', [
            'tariff' => $tariff
        ]);
    }

    /**
     * @param Request $request
     */
    public function report(Request $request)
    {

    }

    public function profit()
    {
        $date = request()->date;


    }
}

app/Http/Controllers/Admin/TariffController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Tariff;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class TariffController extends Controller
{

    /**
     * @return View
     */
    public function index(): View
    {
        return \view('admin.tariff.index', [
            'tariffs' => Tariff::withCount('details')->get()
        ]);
    }

    /**
     * @return View
     */
    public function create(): View
    {
        return \view('admin.tariff.create');
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $request->validate([
            'name'  => 'required',
            'price' => 'required|integer',
        ]);
        $tariff = Tariff::create([
            'name' => $request->name,
            'price' => $request->price,
            'description' => $request->description,
        ]);

        return redirect(route('admin.tariff_details.create', 'id='.$tariff->id));
    }

    /**
     * @param Tariff $tariff
     * @return View
     */
    public function edit(Tariff $tariff): View
    {
        return \view('admin.tariff.edit',[
            'tariff' => $tariff
        ]);
    }

    /**
     * @param Tariff $tariff
     * @param Request $request
     * @return RedirectResponse
     */
    public function update(Tariff $tariff, Request $request): RedirectResponse
    {
        if ($tariff) {
            $tariff->update([
                'name' => $request->name,
                'price' => $request->price,
                'description' => $request->description,
            ]);
            return redirect()->back();
        }
        return redirect()->back();
    }

    /**
     * @param Tariff $tariff
     * @return RedirectResponse
     */
    public function destroy(Tariff $tariff): RedirectResponse
    {
        // TODO
    }



}

resources/views/admin/tariff/create.blade.php
@extends('admin.layouts.admin')

@section('title','Добавить новый тариф')

@section('content')
    <div class="card">
        <div class="card-body">

            <form action="{{ route('admin.tariffs.store') }}" enctype="multipart/form-data" method="post">
                @csrf
                <div class="form-group">
                    <label for="name">Название</label>
                    <input type="text" name="name" id="name" required class="form-control">
                </div>
                <div class="form-group">
                    <label for="price">Цена</label>
                    <input type="number" min="1" name="price" id="price" required class="form-control">
                </div>

                <div class="form-group">
                    <label for="description">Описание</label>
                    <input type="text" name="description" id="description" required class="form-control">
                </div>

                <div class="form-group">
                    <button class="btn btn-success">Создать</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/tariff/detail-create.blade.php
@extends('admin.layouts.admin')

@section('title','Добавить деталь тарифа')

@section('content')
    <div class="card">
        <div class="card-body">

            <form action="{{ route('admin.tariff_details.store') }}" enctype="multipart/form-data" method="post">
                @csrf
                <input type="hidden" name="id" value="{{ request()->id }}">
                <div class="form-group">
                    <label for="name">Название</label>
                    <input type="text"  required class="form-control" disabled value="{{ $tariff->name }}">
                </div>
                <div class="form-group">
                    <label for="price">Цена</label>
                    <input type="number" min="1" disabled value="{{ $tariff->price }}"required class="form-control">
                </div>
                @for($i = 1; $i < 4; $i++)
                    <div class="form-group">
                        <label for="name">Деталь #{{ $i }} {{ $i == 1 ? 'Обязательное поле' : 'Не Обязательное поле' }}</label>
                        <input type="text"  name="detail[{{ $i }}]" {{ $i == 1 ? 'required' : '' }} class="form-control" placeholder="Пример: Без ограничение лайков">
                    </div>
                @endfor



                <div class="form-group">
                    <button class="btn btn-success">Создать</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/tariff/detail-show.blade.php
@extends('admin.layouts.admin')
@section('title', $tariff->name)
@section('topRightContent')
    <a href="{{ route('admin.tariff_details.create','id='.$tariff->id) }}" class="btn btn-primary float-sm-right">Добавить детали</a>
@endsection
@section('content')
    <div class="card">
        <div class="card-body p-0">
            <table class="table table-sm">
                <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>название</th>

                    <th >действие</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($tariff->details as $tariff)
                        <tr>
                            <td>{{ $loop->index + 1 }}</td>
                            <td>{{ $tariff->name }}</td>
                            <td >
                                <a href="{{ route('admin.tariff_details.edit', $tariff->id) }}" class="btn btn-warning">
                                    <ion-icon name="pencil-outline"></ion-icon>
                                </a>

                                <a href="#" onclick="return confirm('Вы уверены ?')" class="btn btn-danger">
                                    <ion-icon name="trash-outline"></ion-icon>
                                </a>
                            </td>
                        </tr>
                    @endforeach

                </tbody>
            </table>


        </div>
    </div>
@endsection

resources/views/admin/tariff/edit.blade.php
@extends('admin.layouts.admin')

@section('title', $tariff->name)

@section('content')
    <div class="card">
        <div class="card-body">

            <form action="{{ route('admin.tariffs.update', $tariff->id) }}" enctype="multipart/form-data" method="post">
                @method('put')
                @csrf
                <div class="form-group">
                    <label for="name">Название</label>
                    <input type="text" name="name" id="name" required class="form-control" value="{{ $tariff->name }}">
                </div>
                <div class="form-group">
                    <label for="price">Цена</label>
                    <input type="number" min="1" name="price" id="price" required class="form-control" value="{{ $tariff->price }}">
                </div>

                <div class="form-group">
                    <label >Описание</label>
                    <input type="text" name="description"  required class="form-control" value="{{ $tariff->description }}">
                </div>



                <div class="form-group">
                    <button class="btn btn-success">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/tariff/index.blade.php
@extends('admin.layouts.admin')
@section('title','Тарифные планы')
@section('topRightContent')
    <a href="{{ route('admin.tariffs.create') }}" class="btn btn-primary float-sm-right">Новый тариф</a>
@endsection
@section('content')
    <div class="card">
        <div class="card-body p-0">
            <table class="table table-sm">
                <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>названия</th>
                    <th>цена</th>
                    <th>Тип</th>
                    <th>Детали</th>
                    <th >действие</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($tariffs as $tariff)
                        <tr>
                            <td>{{ $loop->index + 1 }}</td>
                            <td>{{ $tariff->name }}</td>
                            <td>{{ $tariff->price }}</td>
                            <td>
                                @switch($tariff->type)
                                    @case('wholike')
                                        Кто лайкнул
                                    @break
                                    @case('popular')
                                        Стать популярным
                                    @break
                                    @case('read_message')
                                        Кто прочитал сообщение
                                    @break
                                    @endswitch
                            </td>
                            <td>
                                <a href="{{ route('admin.tariff_details.show', $tariff->id) }}">{{ $tariff->details_count }}</a>
                            </td>
                            <td >
                                <a href="{{ route('admin.tariffs.edit', $tariff->id) }}" class="btn btn-warning">
                                    <ion-icon name="pencil-outline"></ion-icon>
                                </a>

                                <a href="#" onclick="return confirm('Вы уверены ?')" class="btn btn-danger">
                                    <ion-icon name="trash-outline"></ion-icon>
                                </a>
                            </td>
                        </tr>
                    @endforeach

                </tbody>
            </table>


        </div>
    </div>
@endsection

resources/views/admin/tariff/show.blade.php
@extends('admin.layouts.admin')

@section('title',$product->name)

@section('content')

        <div class="card card-solid">
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-sm-6">
                        <div class="card-body">
                            <div class="row">
                                @foreach($images as $img)
                                    <div class="col-sm-2">
                                        <a href="{{asset($img)}}" data-toggle="lightbox" data-title="sample 1 - white" data-gallery="gallery">
                                            <img src="{{asset($img)}}" class="img-fluid mb-2" alt="white sample">
                                        </a>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6">
                        <h3 class="my-3">{{$product->name}}</h3>
                        <hr>
                        <div class="row">
                            <a href="{{route('admin.product.edit',$product->id)}}">edit</a>
                        </div>
                        <table class="table table-bordered">
                           @foreach($params as $param)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$param->param}}</td>
                                    <td>{{$param->value}}</td>
                                </tr>
                           @endforeach

                        </table>



                        <div class="bg-gray py-2 px-3 mt-4">
                            <h2 class="mb-0">
                                {{$product->price}} тенге
                            </h2>
                        </div>




                    </div>
                </div>
                <div class="row mt-4">
                    <nav class="w-100">
                        <div class="nav nav-tabs" id="product-tab" role="tablist">
                            <a class="nav-item nav-link active" id="product-desc-tab" data-toggle="tab" href="#product-desc" role="tab" aria-controls="product-desc" aria-selected="true">Описане</a>
                            <a class="nav-item nav-link" id="product-rating-tab" data-toggle="tab" href="#product-rating" role="tab" aria-controls="product-rating" aria-selected="false">Отзывы</a>
                        </div>
                    </nav>
                    <div class="tab-content p-3" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="product-desc" role="tabpanel" aria-labelledby="product-desc-tab">
                         {!! $product->description !!}
                        </div>
                        <div class="tab-pane fade" id="product-rating" role="tabpanel" aria-labelledby="product-rating-tab">
                            @foreach($reviews as $review)
                                <div class="row">
                                    <div class="col-md-1">
                                        <img class="img-circle" src="{{asset($review->avatar)}}" width="50" alt="">
                                    </div>
                                    <div class="col-md-8">
                                        <h4>{{$review->name}}</h4>
                                        <p> {{$review->text}}
                                        </p>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
    </div>

@endsection

resources/views/admin/tariff/tariff-detail-edit.blade.php
@extends('admin.layouts.admin')

@section('title', $tariff_detail->name)

@section('content')
    <div class="card">
        <div class="card-body">

            <form action="{{ route('admin.tariff_details.update', $tariff_detail->id) }}" enctype="multipart/form-data" method="post">
                @method('put')
                @csrf
                <div class="form-group">
                    <label for="name">Название</label>
                    <input type="text" name="title" id="name" required class="form-control" value="{{ $tariff_detail->name }}">
                </div>

                <div class="form-group">
                    <button class="btn btn-success">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
@endsection