routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\TariffController;
use App\Http\Controllers\Admin\TariffDetailsController;
use App\Http\Controllers\Admin\InterestController;
use App\Http\Controllers\Admin\GenersController;
use App\Http\Controllers\Admin\CountryController;
use App\Http\Controllers\Admin\Analytics\UsersController as AnalyticsUsersController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[LoginController::class,'index'])->name('login');
Route::get('/login',[LoginController::class,'login']);
Route::post('/login',[LoginController::class,'auth'])->name('auth');

Route::group(['prefix' => 'admin', 'middleware'=> ['roles:admin'],'as' => 'admin.'], function () {
    Route::get('/',[AnalyticsUsersController::class, 'mainPage'])->name('list');
    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/',[UsersController::class, 'index'])->name('list');
        Route::get('show/{user}',[UsersController::class, 'show'])->name('show');
        Route::get('/destroy/{user}',[UsersController::class, 'destroy'])->name('destroy');
    });

    Route::resource('tariffs',TariffController::class);
    Route::resource('tariff_details', TariffDetailsController::class);
    Route::resource('interests',  InterestController::class);
    Route::get('interests/destroy/{id}', [InterestController::class,'destroy'])->name('interests.destroy');
    Route::resource('geners', GenersController::class);
    Route::get('geners/list/{zhuz}', [GenersController::class, 'listByZhuz'])->name('geners.list');
    Route::get('delete/{id}', [GenersController::class, 'destroy'])->name('geners.delete');
    Route::group(['prefix' => 'countries', 'as' => 'countries.'], function () {
        Route::get('/',[CountryController::class, 'listOfCountries'])->name('list_of_countries');
        Route::get('create',[CountryController::class, 'createCountry'])->name('create-country');
        Route::post('store-countries', [CountryController::class, 'postCountry'])->name('store-countries');
        Route::any('update-country/{country}', [CountryController::class, 'editCountry'])->name('update-country');

        Route::get('list-cities/{region}',[CountryController::class, 'listOfCities'])->name('list_of_cities');
        Route::get('list-region/{country}',[CountryController::class, 'listOfRegion'])->name('list_of_region');
        Route::get('remove',[CountryController::class, 'remove'])->name('remove');

        Route::get('create-city',[CountryController::class, 'createCity'])->name('create-city');
        Route::get('create-region',[CountryController::class, 'createRegion'])->name('create-region');

        Route::post('store-cities', [CountryController::class, 'postCity'])->name('store-cities');
        Route::any('update-city/{city}', [CountryController::class, 'editCity'])->name('update-city');
        Route::any('update-region/{region}', [CountryController::class, 'editRegion'])->name('update-region');

        Route::post('store-region', [CountryController::class, 'postRegion'])->name('store-region');

    });
});

Route::get('terms', function () {
    echo 'terms';
});

Route::get('privacy', function () {
    echo 'privacy';
});

resources/views/admin/layouts/admin.blade.php
@extends('admin.layouts.base')
@section('theme','sidebar-mini')
@section('wrapper')
    <div class="wrapper">

        <!-- Navbar -->
        @include('admin.layouts.navBar')
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        @include('admin.layouts.sidebar')

        <!-- Content Wrapper. Contains page content -->

        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0">@yield('title')</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            @yield('topRightContent')
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
           <div class="content">
               @yield('content')
           </div>
            <!-- /.content -->
        </div>

        <!-- /.content-wrapper -->

{{--        <!-- Control Sidebar -->--}}
{{--        <aside class="control-sidebar control-sidebar-dark">--}}
{{--            <!-- Control sidebar content goes here -->--}}
{{--            <div class="p-3">--}}
{{--                <h5>Title</h5>--}}
{{--                <p>Sidebar content</p>--}}
{{--            </div>--}}
{{--        </aside>--}}
{{--        <!-- /.control-sidebar -->--}}

        <!-- Main Footer -->
        @include('admin.layouts.footer')
    </div>
@endsection

resources/views/admin/layouts/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title')</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="{{asset('vendor/admin/plugins/fontawesome-free/css/all.min.css')}}">
    <link rel="stylesheet" href="{{asset('vendor/admin/dist/css/adminlte.min.css')}}">
    <link rel="stylesheet" href="{{asset('vendor/admin/plugins/summernote/summernote-bs4.min.css')}}">
</head>
<body class="hold-transition @yield('theme')">

@yield('wrapper')

<!-- jQuery -->
<script src="{{asset('vendor/admin/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{asset('vendor/admin/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('vendor/admin/dist/js/adminlte.min.js')}}"></script>
<script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
<script src="{{asset('vendor/admin/plugins/ekko-lightbox/ekko-lightbox.min.js')}}"></script>
<script src="{{asset('vendor/admin/plugins/summernote/summernote-bs4.min.js')}}"></script>
<script>
    $('#description').summernote()
    $('#terms_of_use').summernote()
    $('#privacy_policy').summernote()
</script>
@stack('js')
</body>
</html>

resources/views/admin/layouts/datatables.blade.php
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>

resources/views/admin/layouts/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2016-2021 <a href="https://1-000.kz">Thousand IT Company</a>.</strong>
</footer>

resources/views/admin/layouts/navBar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
{{--        <li class="nav-item d-none d-sm-inline-block">--}}
{{--            <a href="index3.html" class="nav-link">Home</a>--}}
{{--        </li>--}}
{{--        <li class="nav-item d-none d-sm-inline-block">--}}
{{--            <a href="#" class="nav-link">Contact</a>--}}
{{--        </li>--}}
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Messages Dropdown Menu -->
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>

    </ul>
</nav>

resources/views/admin/layouts/pagination.blade.php
@if ($paginator->lastPage() > 1)
    <ul class="pagination">
        @if($paginator->currentPage() > 1)
            <li class="{{ ($paginator->currentPage() == 1) ? ' disabled' : '' }}">
                <a href="{{ $paginator->url($paginator->currentPage() - 1) }}"><ion-icon name="arrow-back-outline"></ion-icon></a>
            </li>
        @endif
        @for ($i = 1; $i <= $paginator->lastPage(); $i++)
            <li class="{{ ($paginator->currentPage() == $i) ? ' active' : '' }}">
                <a href="{{ $paginator->url($i) }}">{{ $i }}</a>
            </li>
        @endfor
        @if($paginator->currentPage() < $paginator->lastPage())
            <li class="{{ ($paginator->currentPage() == $paginator->lastPage()) ? ' disabled' : '' }}">
                <a href="{{ $paginator->url($paginator->currentPage()+1) }}" ><ion-icon name="arrow-forward-outline"></ion-icon></a>
            </li>
        @endif
    </ul>
@endif

resources/views/admin/layouts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{asset('vendor/admin/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">Админ</a>
            </div>
        </div>

{{--        <!-- SidebarSearch Form -->--}}
{{--        <div class="form-inline">--}}
{{--            <div class="input-group" data-widget="sidebar-search">--}}
{{--                <input class="form-control form-control-sidebar" type="search" placeholder="Search"--}}
{{--                       aria-label="Search">--}}
{{--                <div class="input-group-append">--}}
{{--                    <button class="btn btn-sidebar">--}}
{{--                        <i class="fas fa-search fa-fw"></i>--}}
{{--                    </button>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}

{{--        <!-- Sidebar Menu -->--}}
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">
                <li class="nav-item">
                    <a href="{{ route('admin.list') }}" class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            Главная
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.users.list') }}" class="nav-link">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            Пользователи
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.tariffs.index') }}" class="nav-link">
                        <i class="nav-icon fas fa-list"></i>
                        <p>
                            Тарифы
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.interests.index') }}" class="nav-link">
                        <i class="nav-icon fas fa-calendar"></i>
                        <p>
                            Интересы
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.geners.index') }}" class="nav-link">
                        <i class="nav-icon fas fa-book"></i>
                        <p>
                            Жузы
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.countries.list_of_countries') }}" class="nav-link">
                        <i class="nav-icon fas fa-book"></i>
                        <p>
                            Страна
                        </p>
                    </a>
                </li>

            </ul>
        </nav>
    </div>
</aside>