routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\TariffController;
use App\Http\Controllers\Admin\TariffDetailsController;
use App\Http\Controllers\Admin\InterestController;
use App\Http\Controllers\Admin\GenersController;
use App\Http\Controllers\Admin\CountryController;
use App\Http\Controllers\Admin\Analytics\UsersController as AnalyticsUsersController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[LoginController::class,'index'])->name('login');
Route::get('/login',[LoginController::class,'login']);
Route::post('/login',[LoginController::class,'auth'])->name('auth');

Route::group(['prefix' => 'admin', 'middleware'=> ['roles:admin'],'as' => 'admin.'], function () {
    Route::get('/',[AnalyticsUsersController::class, 'mainPage'])->name('list');
    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/',[UsersController::class, 'index'])->name('list');
        Route::get('show/{user}',[UsersController::class, 'show'])->name('show');
        Route::get('/destroy/{user}',[UsersController::class, 'destroy'])->name('destroy');
    });

    Route::resource('tariffs',TariffController::class);
    Route::resource('tariff_details', TariffDetailsController::class);
    Route::resource('interests',  InterestController::class);
    Route::get('interests/destroy/{id}', [InterestController::class,'destroy'])->name('interests.destroy');
    Route::resource('geners', GenersController::class);
    Route::get('geners/list/{zhuz}', [GenersController::class, 'listByZhuz'])->name('geners.list');
    Route::get('delete/{id}', [GenersController::class, 'destroy'])->name('geners.delete');
    Route::group(['prefix' => 'countries', 'as' => 'countries.'], function () {
        Route::get('/',[CountryController::class, 'listOfCountries'])->name('list_of_countries');
        Route::get('create',[CountryController::class, 'createCountry'])->name('create-country');
        Route::post('store-countries', [CountryController::class, 'postCountry'])->name('store-countries');
        Route::any('update-country/{country}', [CountryController::class, 'editCountry'])->name('update-country');

        Route::get('list-cities/{region}',[CountryController::class, 'listOfCities'])->name('list_of_cities');
        Route::get('list-region/{country}',[CountryController::class, 'listOfRegion'])->name('list_of_region');
        Route::get('remove',[CountryController::class, 'remove'])->name('remove');

        Route::get('create-city',[CountryController::class, 'createCity'])->name('create-city');
        Route::get('create-region',[CountryController::class, 'createRegion'])->name('create-region');

        Route::post('store-cities', [CountryController::class, 'postCity'])->name('store-cities');
        Route::any('update-city/{city}', [CountryController::class, 'editCity'])->name('update-city');
        Route::any('update-region/{region}', [CountryController::class, 'editRegion'])->name('update-region');

        Route::post('store-region', [CountryController::class, 'postRegion'])->name('store-region');

    });
});

Route::get('terms', function () {
    echo 'terms';
});

Route::get('privacy', function () {
    echo 'privacy';
});

app/Models/Gener.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Gener extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = [];

    /**
     * @return HasMany
     */
    public function geners(): HasMany
    {
        return $this->hasMany(Gener::class, 'parent_id');
    }

    public function byZhuz(): HasMany
    {
        return $this->hasMany(Gener::class, 'zhuz');
    }
}

app/Http/Controllers/Admin/GenersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Gener;
use App\Models\Zhuz;
use Illuminate\Http\Request;
use Illuminate\View\View;

class GenersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ulu = Zhuz::withCount('geners')->get();

        return \view('admin.geners.zhuz',[
          'zhuz' => $ulu
        ]);
    }
    public function listByZhuz(Zhuz $zhuz)
    {
       return \view('admin.geners.index', [
            'geners' => Gener::where('parent_id', 0)->where('zhuz_id', $zhuz->id)->withCount('geners')->get(),
            'zhuz' => $zhuz
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (\request()->get('create') == 'under-geners') {
            return \view('admin.geners.create-under', [
                'geners' => Gener::where('parent_id', 0)->get()
            ]);
        }
        return view('admin.geners.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $request->validate([
             'name' => 'required',
         ]);
         if ($request->under_geners == 1) {
             Gener::create([
                 'name' => $request->name,
                 'zhuz' => null,
                 'parent_id' => $request->geners,
             ]);

         }else {
             Gener::create([
                 'name' => $request->name,
                 'zhuz_id' => $request->zhuz,
                 'parent_id' => 0,
             ]);
         }
        return redirect()->back()->with('success','Успешно добавлено');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return \view('admin.geners.under-geners',[
            'geners' => Gener::where('id', $id)->with('geners')->first()
        ]);
    }

    /**
     * @param Gener $gener
     * @return View
     */
    public function edit(Gener $gener): View
    {
        if ($gener->parent_id != 0) {
            return \view('admin.geners.edit', [
                'geners' => Gener::where('parent_id', 0)->get(),
                'gener' => $gener
            ]);
        }
        return view('admin.geners.edit',[
            'gener' => $gener
        ]);
    }

    /**
     * @param Request $request
     * @param Gener $gener
     */
    public function update(Request $request, Gener $gener)
    {
        if ($gener) {
            $gener->update([
                'name' => $request->name,
                'parent_id' => $request->parent_id ?? 0,
                'zhuz_id'   => $request->zhuz_id
            ]);
            return redirect()->back()->with('success','Успешно обновлено');
        }
        return redirect()->back()->with('error','Повторите еще раз');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $gener = Gener::find($id);

        if ($gener) {
            $gener->delete();

            return redirect()->back()->with('success','Успешно удалено');
        }
        return redirect()->back()->with('error','Ошибка');
    }


}

app/Http/Controllers/Api/User/GenerController.php
<?php

namespace App\Http\Controllers\Api\User;

use App\Http\Controllers\Controller;
use App\Http\Resources\GenerResource;
use App\Models\Gener;
use App\Models\Zhuz;
use Illuminate\Http\Request;

class GenerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $geners = Zhuz::all();
        return response()->json([
            'data' => GenerResource::collection($geners)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/geners/create-under.blade.php
@extends('admin.layouts.admin')

@section('title','Добавить ')

@section('content')
    <div class="card">
        <div class="card-body">

            <form action="{{ route('admin.geners.store') }}" enctype="multipart/form-data" method="post">
                @csrf
                <div class="form-group">
                    <label for="name">Название</label>
                    <input type="text" name="name" id="name" required class="form-control">
                </div>
                <div class="form-group">
                    @if(request()->create == 'under-geners')
                        <input type="hidden" name="under_geners" value="1">
                        <label for="name">Выберите ру</label>
                        <select name="geners" class="form-control">
                            @foreach($geners as $item)
                                <option value="{{ $item->id }}"> {{ $item->name }}</option>
                            @endforeach
                        </select>
                    @else
                        <label for="name">Выберите жузы</label>
                        <select name="zhuz" class="form-control">
                            <option value="ulu">Улы жуз</option>
                            <option value="orta">Орта жуз</option>
                            <option value="kishi">Кышы жуз</option>
                            <option value="no">Нет</option>
                        </select>
                    @endif
                </div>
                <div class="form-group">
                    <button class="btn btn-success">Создать</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/geners/create.blade.php
@extends('admin.layouts.admin')

@section('title','Добавить ')

@section('content')
    <div class="card">
        <div class="card-body">

            <form action="{{ route('admin.geners.store') }}" enctype="multipart/form-data" method="post">
                @csrf
                <div class="form-group">
                    <label for="name">Название</label>
                    <input type="text" name="name" id="name" required class="form-control">
                </div>
                <div class="form-group">
                    <label for="name">Выберите жузы</label>
                    <select name="zhuz" class="form-control">
                        <option value="1">Улы жуз</option>
                        <option value="2">Орта жуз</option>
                        <option value="3">Кышы жуз</option>
                    </select>
                </div>
                <div class="form-group">
                    <button class="btn btn-success">Создать</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/geners/edit.blade.php
@extends('admin.layouts.admin')

@section('title', $gener->name)

@section('content')
    <div class="card">
        <div class="card-body">

            <form action="{{ route('admin.geners.update', $gener->id) }}" enctype="multipart/form-data" method="post">
                @method('put')
                @csrf
                <div class="form-group">
                    <label for="name">Название</label>
                    <input type="text" name="name" id="name" required class="form-control" value="{{ $gener->name }}">
                </div>
                <div class="form-group">
                    @if($gener->parent_id != 0)
                        <input type="hidden" name="under_geners" value="1">
                        <label for="name">Выберите ру</label>
                        <select name="parent_id" class="form-control">
                            @foreach($geners as $item)
                                <option value="{{ $item->id }}" {{ $item->id == $gener->parent_id ? 'selected' : '' }}> {{ $item->name }}</option>
                            @endforeach
                        </select>
                    @else
                        <label for="name">Выберите жузы</label>
                        <select name="zhuz" class="form-control">
                            <option value="1" @if($gener->zhuz_id == 1) selected @endif>Улы жуз</option>
                            <option value="2" @if($gener->zhuz_id == 2) selected @endif>Орта жуз</option>
                            <option value="3" @if($gener->zhuz_id == 3) selected @endif>Кышы жуз</option>
                        </select>
                    @endif
                </div>
                <div class="form-group">
                    <button class="btn btn-success">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/geners/index.blade.php
@extends('admin.layouts.admin')
@section('title','Рулар')
@section('topRightContent')
    <a href="{{ route('admin.geners.create') }}" class="btn btn-primary float-sm-right">Добавить </a>

    <a href="{{ route('admin.geners.create', 'create=under-geners') }}" class="btn btn-success float-sm-right mr-1">Добавить под ру</a>
@endsection
@section('content')
    <div class="card">
        <div class="card-body p-0">
            <table class="table table-sm">
                <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Название</th>
                    <th>Жуз</th>
                    <th>Ру</th>
                    <th >действие</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($geners as $item)
                        <tr>
                            <td>{{ $loop->index + 1 }}</td>
                            <td>{{ $item->name }}</td>
                            <td>
                                {{ $zhuz->name }}
                            </td>
                             <td>
                                 <a href="{{ route('admin.geners.show',$item->id) }}">
                                     {{ $item->geners_count }}
                                 </a>
                             </td>
                            <td >
                                <a href="#" class="btn btn-primary">
                                    <ion-icon name="eye-outline"></ion-icon>
                                </a>
                                <a href="{{ route('admin.geners.edit', $item->id) }}" class="btn btn-warning">
                                    <ion-icon name="pencil-outline"></ion-icon>
                                </a>

                                <a href="{{ route('admin.geners.delete', $item->id) }}" onclick="return confirm('Вы уверены ?')" class="btn btn-danger">
                                    <ion-icon name="trash-outline"></ion-icon>
                                </a>
                            </td>
                        </tr>
                    @endforeach

                </tbody>
            </table>


        </div>
    </div>
@endsection

resources/views/admin/geners/show.blade.php
@extends('admin.layouts.admin')

@section('title',$product->name)

@section('content')

        <div class="card card-solid">
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-sm-6">
                        <div class="card-body">
                            <div class="row">
                                @foreach($images as $img)
                                    <div class="col-sm-2">
                                        <a href="{{asset($img)}}" data-toggle="lightbox" data-title="sample 1 - white" data-gallery="gallery">
                                            <img src="{{asset($img)}}" class="img-fluid mb-2" alt="white sample">
                                        </a>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6">
                        <h3 class="my-3">{{$product->name}}</h3>
                        <hr>
                        <div class="row">
                            <a href="{{route('admin.product.edit',$product->id)}}">edit</a>
                        </div>
                        <table class="table table-bordered">
                           @foreach($params as $param)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$param->param}}</td>
                                    <td>{{$param->value}}</td>
                                </tr>
                           @endforeach

                        </table>



                        <div class="bg-gray py-2 px-3 mt-4">
                            <h2 class="mb-0">
                                {{$product->price}} тенге
                            </h2>
                        </div>




                    </div>
                </div>
                <div class="row mt-4">
                    <nav class="w-100">
                        <div class="nav nav-tabs" id="product-tab" role="tablist">
                            <a class="nav-item nav-link active" id="product-desc-tab" data-toggle="tab" href="#product-desc" role="tab" aria-controls="product-desc" aria-selected="true">Описане</a>
                            <a class="nav-item nav-link" id="product-rating-tab" data-toggle="tab" href="#product-rating" role="tab" aria-controls="product-rating" aria-selected="false">Отзывы</a>
                        </div>
                    </nav>
                    <div class="tab-content p-3" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="product-desc" role="tabpanel" aria-labelledby="product-desc-tab">
                         {!! $product->description !!}
                        </div>
                        <div class="tab-pane fade" id="product-rating" role="tabpanel" aria-labelledby="product-rating-tab">
                            @foreach($reviews as $review)
                                <div class="row">
                                    <div class="col-md-1">
                                        <img class="img-circle" src="{{asset($review->avatar)}}" width="50" alt="">
                                    </div>
                                    <div class="col-md-8">
                                        <h4>{{$review->name}}</h4>
                                        <p> {{$review->text}}
                                        </p>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
    </div>

@endsection

resources/views/admin/geners/under-geners.blade.php
@extends('admin.layouts.admin')
@section('title', $geners->name)
@section('topRightContent')
    <a href="{{ route('admin.geners.create') }}" class="btn btn-primary float-sm-right">Добавить </a>

    <a href="{{ route('admin.geners.create', 'create=under-geners') }}" class="btn btn-success float-sm-right mr-1">Добавить под ру</a>
@endsection
@section('content')
    <div class="card">
        <div class="card-body p-0">
            <table class="table table-sm">
                <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Название</th>
                    <th>Ру</th>
                    <th >действие</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($geners->geners as $item)
                        <tr>
                            <td>{{ $loop->index + 1 }}</td>
                            <td>{{ $item->name }}</td>

                             <td>
                                 {{ $geners->name }}
                             </td>
                            <td >
                                <a href="{{ route('admin.geners.edit', $item->id) }}" class="btn btn-warning">
                                    <ion-icon name="pencil-outline"></ion-icon>
                                </a>

                                <a href="{{ route('admin.geners.delete', $item->id) }}" onclick="return confirm('Вы уверены ?')" class="btn btn-danger">
                                    <ion-icon name="trash-outline"></ion-icon>
                                </a>
                            </td>
                        </tr>
                    @endforeach

                </tbody>
            </table>


        </div>
    </div>
@endsection

resources/views/admin/geners/zhuz.blade.php
@extends('admin.layouts.admin')
@section('title','Жузы')
@section('topRightContent')
    <a href="{{ route('admin.geners.create') }}" class="btn btn-primary float-sm-right">Добавить </a>

    <a href="{{ route('admin.geners.create', 'create=under-geners') }}" class="btn btn-success float-sm-right mr-1">Добавить под ру</a>
@endsection
@section('content')
    <div class="card">
        <div class="card-body p-0">
            <table class="table table-sm">
                <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Название</th>
                    <th>Ру</th>
                </tr>
                </thead>
                <tbody>
                @if($zhuz->count() > 0)
                    @foreach($zhuz as $item)
                        <tr>
                            <td>{{ $loop->index +1 }}</td>
                            <td><a href="{{ route('admin.geners.list', $item->id) }}">{{ $item->name }}</a></td>
                            <td>{{ $item->geners_count }}</td>
                        </tr>
                    @endforeach
                    @endif
                </tbody>
            </table>


        </div>
    </div>
@endsection